name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install dependencies
        run: yarn
      - name: run ESLint
        run: yarn run lint
      - name: build project
        run: yarn run build
      - name: run Cypress tests
        uses: cypress-io/github-action@v2
        with: 
          start: yarn start
      - name: save Cypress screenshots on test failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: save Cypress videos 
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
